use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'AHFMFeatureManager_Example' do
  pod 'AHFMFeatureManager', :path => '../'
  
  target 'AHFMFeatureManager_Tests' do
    inherit! :search_paths

    
  end
end
